USE attendance_record;

CREATE TABLE employee (
  ID INT AUTO_INCREMENT PRIMARY KEY,                
  EMPLOYEE_CODE CHAR(6) UNIQUE NOT NULL,         
  NAME VARCHAR(20) NOT NULL,
  PASS VARCHAR(100) NOT NULL
  );

CREATE TABLE admin (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  ADMIN_CODE CHAR(6) UNIQUE NOT NULL,
  NAME VARCHAR(20) NOT NULL,
  PASS VARCHAR(100) NOT NULL
  );

CREATE TABLE record (
  RECORD_ID INT AUTO_INCREMENT PRIMARY KEY,
  EMPLOYEE_ID CHAR(6) NOT NULL,
  WORK_DATE DATE NOT NULL,
  CLOCK_IN TIME NOT NULL,
  CLOCK_OUT TIME,
  UNIQUE (EMPLOYEE_ID, WORK_DATE),
  FOREIGN KEY (EMPLOYEE_ID) REFERENCES employee(EMPLOYEE_CODE)
);

CREATE TABLE break_time (
  BREAK_ID INT AUTO_INCREMENT PRIMARY KEY,
  RECORD_ID INT NOT NULL,             -- record テーブルとのリレーション
  BREAK_START TIME NOT NULL,          -- 休憩開始
  BREAK_END TIME NOT NULL,            -- 休憩終了
  FOREIGN KEY (RECORD_ID) REFERENCES record(RECORD_ID)
);
